name: 'AWS Security Group IP Modifier'
description: 'Add or remove an IP to/from an AWS security group'

inputs:
  role-arn:
    required: true
    description: 'IAM Role ARN to assume'

  aws-region:
    required: true

  security-group-id:
    required: true

  port:
    required: true
    default: '22'

  protocol:
    required: false
    default: 'tcp'

  description:
    required: false
    default: 'GitHub Action IP'

  to-port:
    required: false

  action:
    required: true

runs:
  using: 'composite'
  steps:

  - name: Set up Python
    uses: actions/setup-python@v4
    with:
      python-version: '3.12'

  - name: Install dependencies
    run: |
      python -m pip install --upgrade pip
      pip install boto3 requests
    shell: bash

  - name: Configure AWS credentials via OIDC
    uses: aws-actions/configure-aws-credentials@v4
    with:
      role-to-assume: ${{ inputs.role-arn }}
      aws-region: ${{ inputs.aws-region }}

  - name: Run Python script
    run: |
      TO_PORT_ARG=""
      if [ -n "${{ inputs.to-port }}" ]; then
        TO_PORT_ARG="--to-port ${{ inputs.to-port }}"
      fi

      python3 "${{ github.action_path }}/main.py" \
        --action ${{ inputs.action }} \
        --security-group-id ${{ inputs.security-group-id }} \
        --port ${{ inputs.port }} \
        --protocol ${{ inputs.protocol }} \
        --description "${{ inputs.description }}" \
        --region ${{ inputs.aws-region }} \
        $TO_PORT_ARG
    shell: bash
