name: 'AWS Security Group IP Modifier'
description: 'Add or remove an IP to/from an AWS security group'

inputs:
  all-sec:
    required: true
    description: 'All AWS credentials as secrets (e.g., AWS_ACCESS_KEY_900, AWS_SECRET_ACCESS_KEY_900, etc.)'
  account-id:
    required: true
    description: 'Account ID to use for AWS keys'
  aws-access-key-id:
    required: false
    description: 'AWS Access Key ID'
  aws-secret-access-key:
    required: false
    description: 'AWS Secret Access Key'

  aws-region:
    required: true
    description: 'AWS Region (e.g., us-east-1)'
  security-group-id:
    required: true
    description: 'AWS Security Group ID'
  port:
    required: true
    default: '22'
    description: 'Port to open (e.g., 22)'
  protocol:
    required: false
    default: 'tcp'
    description: 'Protocol for the rule (default: tcp)'
  description:
    required: false
    default: 'GitHub Action IP'
    description: 'Description for the rule'
  to-port:
    required: false
    default: '22'
    description: 'ToPort if different from FromPort'
  action:
    required: true
    description: 'Action to perform: add or remove IP'
runs:
  using: 'composite'
  steps:
  - name: Set up Python
    uses: actions/setup-python@v4
    with:
      python-version: '3.12'

  - name: Install dependencies
    run: |
      python -m pip install --upgrade pip
      pip install boto3 requests
    shell: bash

  # - name: Select IAM Role ARN
  #   id: select-role
  #   run: |
  #     case "${{ inputs.account-id }}" in
  #       365)
  #         echo "ROLE_ARN=${{ secrets.AWS_ROLE_ARN_365 }}" >> $GITHUB_ENV
  #         ;;
  #       019)
  #         echo "ROLE_ARN=${{ secrets.AWS_ROLE_ARN_019 }}" >> $GITHUB_ENV
  #         ;;
  #       *)
  #         echo "Invalid accountid"
  #         exit 1
  #         ;;
  #     esac
  #   shell: bash

  # - name: Configure AWS credentials via OIDC
  #   uses: aws-actions/configure-aws-credentials@v6
  #   with:
  #     role-to-assume: ${{ env.ROLE_ARN }}
  #     aws-region: ${{ inputs.aws-region }}

  - name: Run Python script
    run: |
      TO_PORT_ARG=""
      if [ -n "${{ inputs.to-port }}" ]; then
        TO_PORT_ARG="--to-port ${{ inputs.to-port }}"
      fi

      python3 "${{ github.action_path }}/main.py" \
        --action ${{ inputs.action }} \
        --security-group-id ${{ inputs.security-group-id }} \
        --port ${{ inputs.port }} \
        --protocol ${{ inputs.protocol }} \
        --description "${{ inputs.description }}" \
        --region ${{ inputs.aws-region }} \
        $TO_PORT_ARG
    shell: bash
